### ISSUE TITLE
README, Running Locally, Step 5

### ISSUE THREAD

**Issue by clayford** [LinkedInLearning/python-statistics-essential-training-4433355#3]
In the README under Running Locally, Step 5, I think the instructions for macOS/Linux should say "source env/**Scripts**/activate"

**Comment by mattharrison** [comment]
"Scripts" is a Windows directory. Unixes create a "bin" folder.

**Comment by clayford** [comment]
Gah, I'm an idiot. I was using GitBash on Windows and thought I needed to use the Linux instructions. Sorry for the bother.
